package ikentoo

import (
	"strings"
	"time"
)

type Includes []string

func (i Includes) MarshalSchema() string {
	return strings.Join(i, ",")
}

type Links struct {
	Self struct {
		Href      string `json:"href"`
		Templated bool   `json:"templated"`
	} `json:"self"`
	NextPage struct {
		Href string `json:"href"`
	} `json:"nextPage"`
}

type BusinessList []Business

type Business struct {
	BusinessName      string `json:"businessName"`
	BusinessID        int    `json:"businessId"`
	CurrencyCode      string `json:"currencyCode"`
	BusinessLocations []struct {
		BlName   string `json:"blName"`
		BlID     int64  `json:"blId"`
		Country  string `json:"country"`
		Timezone string `json:"timezone"`
	} `json:"businessLocations"`
}

type Sales []Sale

type Sale struct {
	AccountReference string `json:"accountReference"`
	AccountFiscID    string `json:"accountFiscId"`
	Source           struct {
		InitialAccountID  string `json:"initialAccountId"`
		PreviousAccountID string `json:"previousAccountId"`
	} `json:"source,omitempty"`
	SalesLines []struct {
		ID                       string   `json:"id"`
		TotalNetAmountWithTax    Number   `json:"totalNetAmountWithTax"`
		TotalNetAmountWithoutTax Number   `json:"totalNetAmountWithoutTax"`
		MenuListPrice            Number   `json:"menuListPrice"`
		UnitCostPrice            Number   `json:"unitCostPrice"`
		ServiceCharge            Number   `json:"serviceCharge"`
		ServiceChargeRate        Number   `json:"serviceChargeRate"`
		DiscountAmount           Number   `json:"discountAmount"`
		TaxCode                  string   `json:"taxCode"`
		TaxAmount                Number   `json:"taxAmount"`
		DiscountType             string   `json:"discountType"`
		DiscountCode             string   `json:"discountCode"`
		DiscountName             string   `json:"discountName"`
		AccountDiscountAmount    Number   `json:"accountDiscountAmount"`
		TotalDiscountAmount      Number   `json:"totalDiscountAmount"`
		AccountDiscountType      string   `json:"accountDiscountType"`
		AccountDiscountCode      string   `json:"accountDiscountCode"`
		AccountDiscountName      string   `json:"accountDiscountName"`
		Sku                      string   `json:"sku"`
		Name                     string   `json:"name"`
		NameOverride             string   `json:"nameOverride"`
		StatisticGroup           string   `json:"statisticGroup"`
		Quantity                 Number   `json:"quantity"`
		TaxRatePercentage        Number   `json:"taxRatePercentage"`
		TaxLines                 TaxLines `json:"taxLines"`
		AccountingGroup          struct {
			AccountingGroupID int64  `json:"accountingGroupId"`
			Name              string `json:"name"`
			Code              string `json:"code"`
			StatisticGroup    string `json:"statisticGroup"`
		} `json:"accountingGroup"`
		Currency   string        `json:"currency"`
		Tags       []interface{} `json:"tags"`
		Categories []struct {
			Category string `json:"category"`
			Value    string `json:"value"`
		} `json:"categories"`
		TimeOfSale      time.Time `json:"timeOfSale"`
		DeviceID        int       `json:"deviceId"`
		DeviceName      string    `json:"deviceName"`
		VoidReason      string    `json:"voidReason"`
		ParentLineID    string    `json:"parentLineId,omitempty"`
		RevenueCenter   string    `json:"revenueCenter"`
		RevenueCenterID int       `json:"revenueCenterId"`
		StaffID         int       `json:"staffId"`
		StaffName       string    `json:"staffName"`
	} `json:"salesLines"`
	Payments             Payments  `json:"payments"`
	TimeOfOpening        time.Time `json:"timeOfOpening"`
	TimeOfCloseAndPaid   time.Time `json:"timeOfCloseAndPaid"`
	TableNumber          string    `json:"tableNumber"`
	TableName            string    `json:"tableName"`
	Type                 string    `json:"type"`
	ExternalReferences   []string  `json:"externalReferences,omitempty"`
	NbCovers             float64   `json:"nbCovers"`
	DineIn               bool      `json:"dineIn"`
	DeviceID             int       `json:"deviceId"`
	DeviceName           string    `json:"deviceName"`
	VoidReason           string    `json:"voidReason"`
	ReceiptID            string    `json:"receiptId,omitempty"`
	AccountProfileCode   string    `json:"accountProfileCode"`
	Cancelled            bool      `json:"cancelled"`
	ExternalFiscalNumber string    `json:"externalFiscalNumber"`
	OwnerName            string    `json:"ownerName"`
	OwnerID              int       `json:"ownerId"`
}

type AccountingGroupList []AccountingGroup

type AccountingGroup struct {
	AccountingGroupID int64  `json:"accountingGroupId"`
	Name              string `json:"name"`
	StatisticGroup    string `json:"statisticGroup"`
	Code              string `json:"code"`
}
type PaymentMethodList []PaymentMethod

type PaymentMethod struct {
	Name                string `json:"name"`
	Code                string `json:"code"`
	PmID                int64  `json:"pmId"`
	AccountingReference string `json:"accountingReference,omitempty"`
}

type AutoGenerated struct {
	Embedded struct {
		PaymentMethodList []struct {
		} `json:"paymentMethodList"`
	} `json:"_embedded"`
	Links struct {
		Self struct {
			Href string `json:"href"`
		} `json:"self"`
	} `json:"_links"`
}

type Payments []Payment

type Payment struct {
	Code              string    `json:"code"`
	Description       string    `json:"description"`
	PaymentMethodID   int       `json:"paymentMethodId"`
	NetAmountWithTax  Number    `json:"netAmountWithTax"`
	Currency          string    `json:"currency"`
	Tip               Number    `json:"tip"`
	Consumer          *Consumer `json:"consumer,omitempty"`
	Type              string    `json:"type"`
	DeviceID          int       `json:"deviceId"`
	DeviceName        string    `json:"deviceName"`
	StaffID           int       `json:"staffId"`
	StaffName         string    `json:"staffName"`
	Authorization     string    `json:"authorization"`
	ExternalReference string    `json:"externalReference"`
	RevenueCenter     string    `json:"revenueCenter"`
	RevenueCenterID   int       `json:"revenueCenterId"`
	FiscId            string    `json:"fiscId"`
	UUID              string    `json:"uuid"`
	FiscDate          time.Time `json:"fiscDate"`
	Surcharge         Number    `json:"surcharge"`
}

type Consumer struct {
	ID              int    `json:"id"`
	CustomerID      int    `json:"customerId"`
	Title           string `json:"title"`
	FirstName       string `json:"firstName"`
	LastName        string `json:"lastName"`
	PhoneNumber1    string `json:"phoneNumber1"`
	PhoneNumber2    string `json:"phoneNumber2"`
	CompanyName     string `json:"companyName"`
	AddressLine1    string `json:"addressLine1"`
	AddressLine2    string `json:"addressLine2"`
	ZipCode         string `json:"zipCode"`
	City            string `json:"city"`
	State           string `json:"state"`
	Email           string `json:"email"`
	TaxIdentifier   string `json:"taxIdentifier"`
	FiscalCode      string `json:"fiscalCode"`
	DestinationCode string `json:"destinationCode"`
}

type TaxLines []TaxLine

type TaxLine struct {
	TaxID       string `json:"taxId"`
	TaxCode     string `json:"taxCode"`
	TaxRate     string `json:"taxRate"`
	TaxAmount   string `json:"taxAmount"`
	TaxIncluded bool   `json:"taxIncluded"`
}
